version: '3'
services:
  app:
    container_name: goApp_app
    build:
      context: ./build/app
    volumes:
    - ./code:/code
    ports:
      - 8000:8080
    depends_on:
    - mysql

  mysql:
    container_name: goApp_mysql
    build:
      context: ./build/mysql
    ports:
    - 4306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
